export const MOTIVATIONAL_QUOTES = [
    { text: "A reader lives a thousand lives before he dies. The man who never reads lives only one.", author: "George R.R. Martin" },
    { text: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss" },
    { text: "Reading is to the mind what exercise is to the body.", author: "Richard Steele" },
    { text: "Books are a uniquely portable magic.", author: "Stephen King" },
    { text: "Today a reader, tomorrow a leader.", author: "Margaret Fuller" },
    { text: "Think before you speak. Read before you think.", author: "Fran Lebowitz" },
    { text: "The reading of all good books is like a conversation with the finest minds of past centuries.", author: "René Descartes" },
]

export const TOP_BOOKS = {
    PRODUCTIVITY: [
        { title: "Atomic Habits", author: "James Clear", description: "Tiny changes, remarkable results." },
        { title: "Deep Work", author: "Cal Newport", description: "Rules for focused success in a distracted world." },
        { title: "The 7 Habits of Highly Effective People", author: "Stephen Covey", description: "A step-by-step pathway for living with fairness and integrity." },
        { title: "Getting Things Done", author: "David Allen", description: "The art of stress-free productivity." },
        { title: "Essentialism", author: "Greg McKeown", description: "The disciplined pursuit of less." },
        { title: "The Power of Habit", author: "Charles Duhigg", description: "Why we do what we do in life and business." },
        { title: "Eat That Frog!", author: "Brian Tracy", description: "21 great ways to stop procrastinating." },
        { title: "Make Time", author: "Jake Knapp", description: "How to focus on what matters every day." },
        { title: "Indistractable", author: "Nir Eyal", description: "How to control your attention and choose your life." },
        { title: "Building a Second Brain", author: "Tiago Forte", description: "Organize your digital life." },
    ],
    FINANCE: [
        { title: "The Intelligent Investor", author: "Benjamin Graham", description: "The definitive book on value investing." },
        { title: "Rich Dad Poor Dad", author: "Robert Kiyosaki", description: "What the rich teach their kids about money." },
        { title: "The Psychology of Money", author: "Morgan Housel", description: "Timeless lessons on wealth, greed, and happiness." },
        { title: "Your Money or Your Life", author: "Vicki Robin", description: "9 steps to transforming your relationship with money." },
        { title: "I Will Teach You to Be Rich", author: "Ramit Sethi", description: "No guilt. No excuses. No BS." },
        { title: "The Richest Man in Babylon", author: "George S. Clason", description: "The success secrets of the ancients." },
        { title: "The Total Money Makeover", author: "Dave Ramsey", description: "A proven plan for financial fitness." },
        { title: "Thinking, Fast and Slow", author: "Daniel Kahneman", description: "Insights into how we make decisions." },
        { title: "Broke Millennial", author: "Erin Lowry", description: "Stop scraping by and get your financial life together." },
        { title: "A Random Walk Down Wall Street", author: "Burton Malkiel", description: "The time-tested strategy for successful investing." },
    ],
    COMMUNICATION: [
        { title: "How to Win Friends and Influence People", author: "Dale Carnegie", description: "The only book you need to lead you to success." },
        { title: "Crucial Conversations", author: "Patterson, Grenny, McMillan, Switzler", description: "Tools for talking when stakes are high." },
        { title: "Never Split the Difference", author: "Chris Voss", description: "Negotiating as if your life depended on it." },
        { title: "Talk Like TED", author: "Carmine Gallo", description: "The 9 public-speaking secrets of the world's top minds." },
        { title: "Nonviolent Communication", author: "Marshall Rosenberg", description: "A language of life." },
        { title: "Daring Greatly", author: "Brené Brown", description: "How the courage to be vulnerable transforms the way we live." },
        { title: "Captivate", author: "Vanessa Van Edwards", description: "The science of succeeding with people." },
        { title: "The Art of Communicating", author: "Thich Nhat Hanh", description: "Mindful communication for deeper connections." },
        { title: "Difficult Conversations", author: "Stone, Patton, Heen", description: "How to discuss what matters most." },
        { title: "Surrounded by Idiots", author: "Thomas Erikson", description: "The four types of human behavior." },
    ],
    PERSONAL_GROWTH: [
        { title: "Man's Search for Meaning", author: "Viktor Frankl", description: "The classic tribute to hope from the Holocaust." },
        { title: "Mindset", author: "Carol Dweck", description: "The new psychology of success." },
        { title: "Can't Hurt Me", author: "David Goggins", description: "Master your mind and defy the odds." },
        { title: "The Alchemist", author: "Paulo Coelho", description: "A fable about following your dream." },
        { title: "Meditations", author: "Marcus Aurelius", description: "The writings of a Roman Emperor." },
        { title: "The Subtle Art of Not Giving a F*ck", author: "Mark Manson", description: "A counterintuitive approach to living a good life." },
        { title: "Big Magic", author: "Elizabeth Gilbert", description: "Creative living beyond fear." },
        { title: "Quiet", author: "Susan Cain", description: "The power of introverts in a world that can't stop talking." },
        { title: "The Four Agreements", author: "Don Miguel Ruiz", description: "A practical guide to personal freedom." },
        { title: "Start with Why", author: "Simon Sinek", description: "How great leaders inspire everyone to take action." },
    ]
}
